image_grabber:
  ros__parameters:
    image_width: 1280
    image_height: 720
    fps: 15.0
    image_publishing_rate: 15.0
    publish_raw_stream: false
    publish_full_res: false
    publish_monitor_stream: false
    publish_compressed_stream: true
    compressed_quality: 70
    monitor_width: 640
    monitor_height: 360
    shutter_speed: 1000
    wb_mode: 6
    camera_info_file: "arducam_info.yaml"
    enable_timelapse: false
    save_dir: "/tmp/camera_captures_calibrated"
    save_interval_sec: 1.0
