mission_sequence:
  on_failure: abort_and_rtl
  missions:
    - type: takeoff
      name: takeoff
      config:
        target_altitude_m: 15.24

    - type: gps_waypoint
      name: circuit_time_trial
      config:
        waypoint_file: ../waypoints/competition_waypoints.yaml
        waypoint_altitude_m: 15.24
        arrival_radius_m: 4.0
        arrival_alt_tolerance_m: 2.0
        hold_time_s: 0.0
        desired_yaw_deg: 90.0
        mode: circuit_time_trial

    - type: rtl
      name: rtl
      config:
        rtl_mode: "RTL"
